apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

commonLabels:
  purpose: Argocd-demo
  env : prod

#namePrefix: prod-

replicas:
  - name: web-frontend
    count: 3
  - name: customers-v2
    count: 4


patches:
  - target:
      kind: Deployment
      name: web-frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: 'http://customers.prod-app.svc.cluster.local'
  - target:
      kind: Deployment
      name: web-frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: 'ruchabhange/frontend-image:686970aaec9db6dad12a3b7946801935978a3196'
  - target:
      kind: Deployment
      name: customers-v2
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: 'ruchabhange/backend-image:686970aaec9db6dad12a3b7946801935978a3196'
