apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-v2
  labels:
    app: customers
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
      version: v2
  template:
    metadata:
      labels:
        app: customers
        version: v2
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - image: gcr.io/tetratelabs/customers:9d800fe50ab4f82fe1121a29a8ca9cc258a0294d
          imagePullPolicy: Always
          name: svc
          ports:
            - containerPort: 3000


---
kind: Service
apiVersion: v1
metadata:
  name: customers
  labels:
    app: customers
spec:
  selector:
    app: customers
  ports:
    - port: 80
      name: http
      targetPort: 3000
