name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Building and Pushing the Image
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: File changes for customers
      id: customers
      uses: tj-actions/changed-files@v34
      with:
        files: |
            /application/customers/**
    
    - name: File changes for web-frontend
      id: web-fronend
      uses: tj-actions/changed-files@v34
      with:
        files: |
            /application/web-frontend/**
  
    -  name: Build and push customer image
       if: steps.customers.outputs.any_changed == 'true'
       env:
         image-name-customers: backend-image
         
       id: build-and-push-customer-image
       uses: docker/build-push-action@v3
       with:
        context: ./application/customers
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.image-name-customers }}:${{ github.sha }}
    -  name: Build and push webfrontend
       if: steps.web-fronend.outputs.any_changed == 'true'
       env:
         image-name-web-frontend: frontend-image
       id: build-and-push-webfrontend-image
       uses: docker/build-push-action@v3
       with:
        context: ./application/web-frontend
        push: true
        build-args: |
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.image-name-web-frontend }}:${{ github.sha }}
    -  name: Update Version for customer image
       if: steps.customers.outputs.any_changed == 'true'
       run: |
          version=$(cat ./application/kustomize-manifest/overlays/prod/kustomization.yaml | grep backend-image: | awk '{print $2}' | cut -d ':' -f 2 | rev | cut -c2- | rev)
          echo "$version for Production envirornment"
          sed -i "s/$version/${{ github.sha }}/" ./application/kustomize-manifest/overlays/prod/kustomization.yaml
          cat ./application/kustomize-manifest/overlays/prod/kustomization.yaml | grep backend-image: | awk '{print $2}'
          version=$(cat ./application/kustomize-manifest/overlays/test/kustomization.yaml | grep backend-image: | awk '{print $2}' | cut -d ':' -f 2 | rev | cut -c2- | rev)
          echo "$version for test enviornment"
          sed -i "s/$version/${{ github.sha }}/" ./application/kustomize-manifest/overlays/test/kustomization.yaml
          cat ./application/kustomize-manifest/overlays/test/kustomization.yaml | grep backend-image: | awk '{print $2}' 
    
    -  name: Update Version for webfrontend image
       if: steps.web-fronend.outputs.any_changed == 'true'
       run: |
          version=$(cat ./application/kustomize-manifest/overlays/prod/kustomization.yaml | grep frontend-image: | awk '{print $2}' | cut -d ':' -f 2 | rev | cut -c2- | rev)
          echo "$version for Production envirornment"
          sed -i "s/$version/${{ github.sha }}/" ./application/kustomize-manifest/overlays/prod/kustomization.yaml
          cat ./application/kustomize-manifest/overlays/prod/kustomization.yaml | grep frontend-image: | awk '{print $2}'
          version=$(cat ./application/kustomize-manifest/overlays/test/kustomization.yaml | grep frontend-image: | awk '{print $2}' | cut -d ':' -f 2 | rev | cut -c2- | rev)
          echo "$version for test enviornment"
          sed -i "s/$version/${{ github.sha }}/" ./application/kustomize-manifest/overlays/test/kustomization.yaml
          cat ./application/kustomize-manifest/overlays/test/kustomization.yaml | grep frontend-image: | awk '{print $2}' 
    -  name: Commit and push changes
       uses: devops-infra/action-commit-push@v0.3
       with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Image version updated
